### ISSUE TITLE
Error: Insufficient values in manual scale. 110 needed but only 74 provided.

### ISSUE THREAD

**Issue by abadgerw** [daisybio/PRONE.Shiny#5]
I was testing a large dataset with your great application and ran into the error mentioned in the title when trying to graph outlier visualizations and normalization plots.

**Comment by lisiarend** [comment]
Hey @abadgerw,

Great to see you using our tool! I believe you’re our first official user. :)

PRONE is still under development, so I’ll look into the error you’ve encountered and assist with your data analysis. I’ll get back to you once the bug is fixed.

Best,
Lis

**Comment by lisiarend** [comment]
Hey @abadgerw,

new version of PRONE deployed with colors being subsampled when more than in color palette. Additionally, I included a novel feature to select the color palette the user wants to use. In the bar on the top, there is now a button for this.

Best,
Lis
