### ISSUE TITLE
Normalization Failed

### ISSUE THREAD

**Issue by abadgerw** [daisybio/PRONE.Shiny#6]
I tried running all normalization methods on my data and got a failure message that stated: return code from pthread_create() is 22. Any insight into why this is happening?

**Comment by lisiarend** [comment]
Hey @abadgerw,

The issue you’re experiencing is likely due to the Quantile normalization method. There’s a related issue here: https://github.com/Bioconductor/bioconductor_docker/issues/22. It seems to be a problem with package versioning. I’ll look into this and notify you once the Shiny App is updated.

Best,
Lis

**Comment by abadgerw** [comment]
Thank you! I started checking normalization methods one by one and noticed that both Normics methods were throwing an error indicating that the top protein value was null even though it was being set in the GUI.

**Comment by lisiarend** [comment]
I will check this as well. Thank you very much for testing it. If you find any other bugs, please add them here, and I will try to fix them. The first real user always discovers bugs that are invisible to the developer;)

Additionally, we have not yet tested the Shiny app with such a large dataset, so it is very interesting to see if it will handle it without breaking. It's likely that some visualizations may not be as suitable and comprehensive with such a high amount of samples.

Can I just ask you a question. How did you come across PRONE? We are currently preparing a manuscript and I was curious about how you found it?

Best,
Lis

**Comment by abadgerw** [comment]
Thank you! I stumbled upon your vignettes while google searching normalization methods for proteomics.

**Comment by abadgerw** [comment]
Last thing: I do find that cyclic loess PMAD, etc looks very different in your software compared to NormalyzerDE. In NormalyzerDE, cyclic loess demonstrates the best performance on my data but poor performance with PRONE. Any idea why there is a discrepancy?

**Comment by lisiarend** [comment]
Can you provide an example picture showcasing PMAD of PRONE and NormalyzerDE

**Comment by abadgerw** [comment]
![image](https://github.com/user-attachments/assets/a77a63f9-2b93-4fd3-a0fd-c0702fea3e05)

![image](https://github.com/user-attachments/assets/b8e24d75-b436-4738-9eab-802aa1efd8ac)

![image](https://github.com/user-attachments/assets/3165084e-945b-4e33-a7c7-a8db7d13d698)

![image](https://github.com/user-attachments/assets/5e9eedaf-dec1-41f4-9852-71e74bfc903e)

**Comment by lisiarend** [comment]
I will have a look at this too. I will write you next week once I had time to check on all your comments.

**Comment by lisiarend** [comment]
> Last thing: I do find that cyclic loess PMAD, etc looks very different in your software compared to NormalyzerDE. In NormalyzerDE, cyclic loess demonstrates the best performance on my data but poor performance with PRONE. Any idea why there is a discrepancy?

I checked this. 

In performCyclicLoessNormalization() of NormalyzerDE, they call limma::normalizeCyclicLoess(log2Matrix, method = "fast").

However, this is not the cyclic version of the local regression normalization but the fast local regression method.

In PRONE:
- LoessCyc uses the limma function with method = "pairs"
- LoessF uses the limma function with method = "fast"

Hence, to compare NormalyzerDE and PRONE, you should compare CyclicLoess of NormalyzerDE to LoessF of PRONE. I checked both functions with an example data set and they are giving the same results for my case.

**Comment by abadgerw** [comment]
Fantastic! To summarize and keep organized, the only outstanding things I noticed were:

1. The quantile normalization issue with pthread_create()

2. Normics normalization error (see image below)

![image](https://github.com/user-attachments/assets/1de67fbb-60ca-46b2-b783-6325a9b3b49f)

2. Graphing errors (see images below)

![image](https://github.com/user-attachments/assets/04b08270-0ecd-4d0c-878d-11e9cf599f9b)

![image](https://github.com/user-attachments/assets/89014094-050a-4e8b-945c-864851c20204)

**Comment by lisiarend** [comment]
Hey @abadgerw,

a new version of PRONE is now available. All problems should be resolved now.

If some persist of new problems arise for your data set, feel free to open a new issue.

Best,
Lis
