### ISSUE TITLE
Data Loading Issues

### ISSUE THREAD

**Issue by abadgerw** [daisybio/PRONE.Shiny#7]
Thank you for implementing changes so quickly! I tried to test them by uploading my data but have no run into an error when loading that I didn't see beforehand (screenshot attached). Any insight as I was able to successfully load the same files previously? 

![image](https://github.com/user-attachments/assets/234374cd-bd6f-465f-b772-e3cf22c76e19)

**Comment by lisiarend** [comment]
I fixed this again! New version is online:)

Thank you for testing!

**Comment by abadgerw** [comment]
Thank you! I've done some more testing and found the following plots give an error:

![image](https://github.com/user-attachments/assets/71d4c57c-40a5-4419-a452-adc3490d51e4)

![image](https://github.com/user-attachments/assets/27c125d4-b108-4f7d-9368-cc95b8a16444)

![image](https://github.com/user-attachments/assets/a0d51424-2ce7-468b-9e52-5a4aa8688492)

In addition, I noticed the DE analysis lags and never completes. Any thoughts on that?

**Comment by lisiarend** [comment]
Would it be possible for you to send me the SummarizedExperiment object of your data via email or so?

Because the plots and DE analysis complete with my data, and this would make the debugging much easier.

**Comment by abadgerw** [comment]
@lisiarend sharing test data and metadata files here.

[Test_Metadata.csv](https://github.com/user-attachments/files/16471936/Test_Metadata.csv)
[Test_Data.csv](https://github.com/user-attachments/files/16471937/Test_Data.csv)

**Comment by lisiarend** [comment]
Thank you very much. I will be on vacation next week and come back to you as soon as possible!

**Comment by lisiarend** [comment]
Hey @abadgerw,

sorry for being a bit late. I fixed the bugs visible on the figures. Hopefully now everything is fixed for your data analysis. If not, just open another issue:)

Best,
Lis
